Repository devkeon/dong-geul-be, pull requests merged in 2024-10, with the labels that each got.

#9 [chore] CI/CD 워크플로우 작성 및 Docker 파일 환경 변수 적용
  .github/workflows/main_deploy.yml
  docker-compose.yml
Labels: CHORE

#11 Feat/2 게시판 기능 추가
  src/main/java/com/nemo/dong_geul_be/board/controller/BoardDGController.java
  src/main/java/com/nemo/dong_geul_be/board/controller/BoardJJController.java
  src/main/java/com/nemo/dong_geul_be/board/domain/dto/request/CreatePostRequest.java
  src/main/java/com/nemo/dong_geul_be/board/domain/dto/response/PostDTO.java
  src/main/java/com/nemo/dong_geul_be/board/domain/dto/response/PostDetailResponse.java
  src/main/java/com/nemo/dong_geul_be/board/domain/entity/Comment.java
  src/main/java/com/nemo/dong_geul_be/board/domain/entity/Post.java
  src/main/java/com/nemo/dong_geul_be/board/domain/entity/Post_IMG.java
  src/main/java/com/nemo/dong_geul_be/board/repository/CommentRepository.java
  src/main/java/com/nemo/dong_geul_be/board/repository/PostRepository.java
  src/main/java/com/nemo/dong_geul_be/board/service/CommentService.java
  src/main/java/com/nemo/dong_geul_be/board/service/PostService.java
Labels: FEAT

#14 [Feature] mypage 기능 추가
  src/main/java/com/nemo/dong_geul_be/clubAndHeadmem/ClubAndHeadMem.java
  src/main/java/com/nemo/dong_geul_be/clubAndHeadmem/ClubRepository.java
  src/main/java/com/nemo/dong_geul_be/csv/CSVDataLoader.java
  src/main/java/com/nemo/dong_geul_be/member/domain/entity/Member.java
  src/main/java/com/nemo/dong_geul_be/member/domain/entity/Role.java
  src/main/java/com/nemo/dong_geul_be/mypage/MyPageConverter.java
  src/main/java/com/nemo/dong_geul_be/mypage/controller/MyPageController.java
  src/main/java/com/nemo/dong_geul_be/mypage/domain/IsConfirmed.java
  src/main/java/com/nemo/dong_geul_be/mypage/domain/MyClub.java
  src/main/java/com/nemo/dong_geul_be/mypage/dto/MyPageRequest.java
  src/main/java/com/nemo/dong_geul_be/mypage/dto/MyPageResponse.java
  src/main/java/com/nemo/dong_geul_be/mypage/repository/MyClubRepository.java
  src/main/java/com/nemo/dong_geul_be/mypage/service/MyPageService.java
  src/main/resources/csv/club.csv
Labels: FEAT

#20 [chore, feat] Qurey DSL 을 이용한 게시물 검색 기능 추가
  build.gradle
  src/main/java/com/nemo/dong_geul_be/Search/QueryDslConfig.java
  src/main/java/com/nemo/dong_geul_be/Search/controller/SearchController.java
  src/main/java/com/nemo/dong_geul_be/Search/repository/PostRepositoryCustom.java
  src/main/java/com/nemo/dong_geul_be/Search/repository/PostRepositoryCustomImpl.java
  src/main/java/com/nemo/dong_geul_be/Search/service/SearchLogService.java
  src/main/java/com/nemo/dong_geul_be/Search/service/SearchService.java
  src/main/java/com/nemo/dong_geul_be/board/domain/dto/response/PostDTO.java
  src/main/java/com/nemo/dong_geul_be/board/repository/PostRepository.java
Labels: CHORE, FEAT

#18 [fix] main_deploy.yml 수정
  .github/workflows/main_deploy.yml
Labels: FIX, CHORE

#15 Feature: 로그인 기능 추가
  src/main/java/com/nemo/dong_geul_be/DongGeulBeApplication.java
  src/main/java/com/nemo/dong_geul_be/authentication/domain/JwtMemberDetail.java
  src/main/java/com/nemo/dong_geul_be/authentication/domain/LoginSuccessResponse.java
  src/main/java/com/nemo/dong_geul_be/authentication/filter/JsonAuthenticationFilter.java
  src/main/java/com/nemo/dong_geul_be/authentication/filter/JwtAuthenticationFilter.java
  src/main/java/com/nemo/dong_geul_be/authentication/handler/jwt/LoginFailureHandler.java
  src/main/java/com/nemo/dong_geul_be/authentication/handler/jwt/LoginSuccessHandler.java
  src/main/java/com/nemo/dong_geul_be/authentication/service/LoginService.java
  src/main/java/com/nemo/dong_geul_be/authentication/util/JwtTokenUtil.java
  src/main/java/com/nemo/dong_geul_be/authentication/util/JwtTokenUtilImpl.java
  src/main/java/com/nemo/dong_geul_be/authentication/util/SecurityContextUtil.java
  src/main/java/com/nemo/dong_geul_be/authentication/util/SimpleSecurityContextUtil.java
  src/main/java/com/nemo/dong_geul_be/global/config/SecurityConfig.java
Labels: FEAT

#23 [chore] CI/CD Workflow 일부 수정
  .github/workflows/main_deploy.yml
Labels: FIX, CHORE

#24 [feat] 메인 페이지 기능 구현
  src/main/java/com/nemo/dong_geul_be/mainpage/controller/MainPageController.java
  src/main/java/com/nemo/dong_geul_be/mainpage/dto/MainPageBoardResponse.java
  src/main/java/com/nemo/dong_geul_be/mainpage/repository/MainPostRepository.java
  src/main/java/com/nemo/dong_geul_be/mainpage/service/MainPageService.java
  src/main/java/com/nemo/dong_geul_be/mainpage/service/MainPageServiceImpl.java
Labels: FEAT
